package com.nilaapps.adaptive.crypto;

/**
 * Wire format for an encrypted API response.
 * The client already holds the AES key it generated for the request,
 * so we only need to send the ciphertext and a fresh IV.
 *   encryptedData  - Base64(AES-256-CBC(responseJson))
 *   iv             - Base64(16-byte fresh IV generated by server for this response)
 */
public class EncryptedApiResponse {
    private String encryptedData;
    private String iv;

    public EncryptedApiResponse() {}
    public EncryptedApiResponse(String encryptedData, String iv) {
        this.encryptedData = encryptedData;
        this.iv = iv;
    }

    public String getEncryptedData() { return encryptedData; }
    public void setEncryptedData(String v) { this.encryptedData = v; }
    public String getIv() { return iv; }
    public void setIv(String v) { this.iv = v; }
}
